-- Ontology Schema: Configurable entity types and relationship types
-- Replaces hardcoded constants in frontend with database-driven configuration

CREATE TABLE IF NOT EXISTS ontology_domains (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  domain_code TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  description TEXT,
  color TEXT NOT NULL DEFAULT '#64748b',
  initials TEXT NOT NULL DEFAULT '?',
  icon TEXT DEFAULT '📄',
  properties JSONB DEFAULT '[]',
  enabled BOOLEAN DEFAULT true,
  priority INT DEFAULT 50,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ontology_relationships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  relationship_code TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  description TEXT,
  color TEXT NOT NULL DEFAULT '#64748b',
  abbreviation TEXT NOT NULL DEFAULT '???',
  source_domain TEXT,
  target_domain TEXT,
  is_structural BOOLEAN DEFAULT false,
  enabled BOOLEAN DEFAULT true,
  priority INT DEFAULT 50,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ontology_domains_enabled ON ontology_domains(enabled);
CREATE INDEX IF NOT EXISTS idx_ontology_rels_enabled ON ontology_relationships(enabled);

-- Seed with current hardcoded domain types
INSERT INTO ontology_domains (domain_code, label, description, color, initials, icon, priority) VALUES
  ('ELECTRONIC_CIRCUIT', 'Electronic Circuit', 'IC design files, schematics, layout drawings, netlists', '#8b5cf6', 'E', '🔲', 10),
  ('PDF_DOCUMENT', 'PDF Document', 'Portable Document Format files — reports, datasheets, specifications', '#ef4444', 'P', '📄', 20),
  ('OFFICE_DOCUMENT', 'Office Document', 'Word, Excel, PowerPoint — presentations, spreadsheets, memos', '#3b82f6', 'O', '📊', 30),
  ('AUDIO', 'Audio Recording', 'Meeting recordings, voice memos, podcast episodes', '#10b981', 'A', '🎙️', 40),
  ('VIDEO', 'Video Content', 'Video recordings, screen captures, training materials', '#14b8a6', 'V', '🎬', 50),
  ('STRUCTURED_DATA', 'Database Table', 'SQL database tables, views — structured data from relational databases', '#f97316', 'D', '🗃️', 55),
  ('IMAGE', 'Image', 'Images, scans, diagrams, screenshots — text extracted via Claude Vision OCR', '#0891b2', 'I', '🖼️', 56)
ON CONFLICT (domain_code) DO NOTHING;

-- Seed with current hardcoded relationship types
INSERT INTO ontology_relationships (relationship_code, label, description, color, abbreviation, is_structural, priority) VALUES
  ('DOCUMENTS_CIRCUIT', 'Documents Circuit', 'Office document that describes or documents a circuit design', '#8b5cf6', 'DOC', false, 10),
  ('DISCUSSES_DESIGN', 'Discusses Design', 'Content that discusses or references a design artifact', '#10b981', 'DIS', false, 20),
  ('PRESENTS_DESIGN', 'Presents Design', 'Presentation or report that presents design information', '#3b82f6', 'PRS', false, 30),
  ('REFERENCES_IP', 'References IP', 'Document that references intellectual property or IP blocks', '#f59e0b', 'REF', false, 40),
  ('DERIVED_FROM', 'Derived From', 'Asset derived from or generated by another asset', '#ec4899', 'DER', false, 50),
  ('SHARES_ENTITY', 'Shares Entity', 'Assets sharing common entities (part numbers, emails, references)', '#6366f1', 'SHR', false, 60),
  ('TAGGED_WITH', 'Tagged With', 'Asset tagged with a business glossary concept', '#a855f7', 'TAG', false, 70),
  ('SAME_PROJECT', 'Same Project', 'Assets belonging to the same governance project', '#334155', 'PRJ', true, 80),
  ('BELONGS_TO', 'Belongs To', 'Structural: asset belongs to a project', '#1e293b', 'BLG', true, 90),
  ('SAME_ENTITY', 'Same Entity', 'Assets sharing the same entity in the same domain', '#64748b', 'ENT', true, 95),
  ('FOREIGN_KEY', 'Foreign Key', 'Database table foreign key constraint linking two tables', '#f97316', 'FK', false, 15),
  ('INFERRED_JOIN', 'Inferred Join', 'AI-inferred join relationship between database tables', '#fb923c', 'INF', false, 16)
ON CONFLICT (relationship_code) DO NOTHING;
