name: Build and Push to ACR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.acrdemocontainer.azurecr.io }}
          username: ${{ secrets.acrdemocontainer }}
          password: ${{ secrets.Dj6VUvQ3P7KyJOgBmtM4wCNaoH6n4WWSptMvKHBSgPlUxIZ4BhpXJQQJ99CEACqBBLyEqg7NAAACAZCRmo4W }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/cude:latest
